tools:
  jdk:
    - 1.8.0_102-b14
  gradle:
    - 2.14.1

flows:
  master:
    - call: sdk
    - (on master, name hello-android) ./gradlew compileDebugSources
  sdk:
    - echo "sdk.dir=/Users/rreda/Library/Android/sdk" > local.properties
  pr:
  - call: master

